name: HiClans
main: serenity\ClanPlugin
version: 2
api: 4.0.0
author: serenity-Sun
commands:
  clan:
    description: open clan form
    permission: clan.Command
permissions:
  clan.command:
    default: op